Initial tuktuk buildout
helium/tuktuk pull request #1
Opened 2024-11-25 20:33 UTC by ChewingGlass

2025-01-21 18:30 UTC, ChewingGlass commented
/canary-release

2025-01-28 22:31 UTC, bryzettler requested changes
Would do a quick search for `refund` and `rent_refund` and consolidate them to the same choice

2025-01-28 22:31 UTC, bryzettler commented on solana-programs/programs/tuktuk/src/instructions/close_task_queue_v0.rs
> +    pub refund: AccountInfo<'info>,
`refund` or `rent_refund`

2025-01-28 22:46 UTC, ChewingGlass commented on .github/actions/setup-anchor/action.yaml
> +        key: anchor-cli-${{ runner.os }}-v0003-${{ env.ANCHOR_VERSION }}-${{ env.ANCHOR_SHA }}
Not needed since we're on newer anchor I think

2025-02-10 19:57 UTC, bryzettler approved these changes

2025-02-10 21:50 UTC, merged